apiVersion: batch/v1
kind: Job
metadata:
  name: chaos-test-case
  labels:
    app: chaos-test-case
spec:
  template:
    spec:
      containers:
        - name: chaos-test-case
          image: dm:chaos # build this image in GitHub action workflow
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 80
              name: chaos-test-case
          command:
            - "/chaos-case"
            - "--master-addr=dm-master.$(MY_POD_NAMESPACE)" # use the address of the DM-master service
      restartPolicy: Never
  backoffLimit: 0 # fail immediately
